version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: superset_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
  superset_home: